init_config:

# To notify on every service, set a list of notified uses here.
#
   notify:
         - all
#        - user1@example.com
#        - pagerduty

instances:
  - name: mitrocore_healthcheck
    url: http://localhost:8080/mitro-core/admin/healthcheck

  # DISABLED: This wa too flaky. Python bug?
  # - name: primary_from_secondary
  #   url: https://www.mitro.co/favicon.ico
  #   threshold: 2
  #   timeout: 30

    # TODO: Add static content to secondary; monitor that?
  # - name: secondary_nginx
  #   url: https://secondary.mitro.ca/mitro-core/api/BuildMetadata
  #   threshold: 2
  #   timeout: 30

#    -   name: My first service
#        url: http://some.url.example.com
#        timeout: 1

         # If your service uses basic authentication, you can optionally
         # specify a username and password that will be used in the check.
#        username: user
#        password: pass

         # The (optional) window and threshold parameters allow you to trigger
         # alerts only if the check fails x times within the last y attempts
         # where x is the threshold and y is the window.

#        threshold: 3
#        window: 5

         # The (optional) include_content parameter will instruct the check
         # to include the first 200 characters of the HTTP response body
         # in notifications sent by this plugin. This is best used with
         # "healthcheck"-type URLs, where the body contains a brief, human-
         # readable summary of failure reasons in the case of errors. This
         # defaults to false.

#        include_content: true

         # The (optional) collect_response_time parameter will instruct the
         # check to create a metric 'network.http.response_time', tagged with
         # the url, reporting the response time in seconds.

#        collect_response_time: true

         # The (optional) headers parameter allows you to send extra headers
         # with the request. This is useful for explicitly specifying the host
         # header or perhaps adding headers for authorisation purposes. Note
         # that the http client library converts all headers to lowercase.
         # This is legal according to RFC2616
         # (See: http://tools.ietf.org/html/rfc2616#section-4.2)
         # but may be problematic with some HTTP servers
         # (See: https://code.google.com/p/httplib2/issues/detail?id=169)

#        headers:
#           Host: alternative.host.example.com
#           X-Auth-Token: SOME-AUTH-TOKEN

#        tags:
#            - url:http://alternative.host.example.com
#            - env:production


#    -   name: My second service
#        url: https://another.url.example.com

         # For service-specific notifications, you can optionally specify
         # a list of users to notify within the service configuration.
#        notify:
#           - user2@example.com
#           - pagerduty
